language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov
  - pip install flake8
  - pip install radon
script:
  - coverage run test.py
  - codecov
  - flake8 --ignore=E501  # ignore "line too long errors"
  - radon cc ./metermonitor/ -a
  - radon mi .
  - radon raw . -s
notifications:
  email:
    on_success: never
    on_failure: always